// Code generated by protoc-gen-go. DO NOT EDIT.
// source: access_token_proto/access_token.proto

package access_token_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccessToken struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_4587e33829422684, []int{0}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AccessToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type UserID struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_4587e33829422684, []int{1}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AccessTokenCheck struct {
	AccessToken          *AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AccessTokenCheck) Reset()         { *m = AccessTokenCheck{} }
func (m *AccessTokenCheck) String() string { return proto.CompactTextString(m) }
func (*AccessTokenCheck) ProtoMessage()    {}
func (*AccessTokenCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_4587e33829422684, []int{2}
}

func (m *AccessTokenCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenCheck.Unmarshal(m, b)
}
func (m *AccessTokenCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenCheck.Marshal(b, m, deterministic)
}
func (m *AccessTokenCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenCheck.Merge(m, src)
}
func (m *AccessTokenCheck) XXX_Size() int {
	return xxx_messageInfo_AccessTokenCheck.Size(m)
}
func (m *AccessTokenCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenCheck.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenCheck proto.InternalMessageInfo

func (m *AccessTokenCheck) GetAccessToken() *AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

type AccessTokenGet struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessTokenGet) Reset()         { *m = AccessTokenGet{} }
func (m *AccessTokenGet) String() string { return proto.CompactTextString(m) }
func (*AccessTokenGet) ProtoMessage()    {}
func (*AccessTokenGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_4587e33829422684, []int{3}
}

func (m *AccessTokenGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenGet.Unmarshal(m, b)
}
func (m *AccessTokenGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenGet.Marshal(b, m, deterministic)
}
func (m *AccessTokenGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenGet.Merge(m, src)
}
func (m *AccessTokenGet) XXX_Size() int {
	return xxx_messageInfo_AccessTokenGet.Size(m)
}
func (m *AccessTokenGet) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenGet.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenGet proto.InternalMessageInfo

func (m *AccessTokenGet) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

type AccessTokenCreate struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessTokenCreate) Reset()         { *m = AccessTokenCreate{} }
func (m *AccessTokenCreate) String() string { return proto.CompactTextString(m) }
func (*AccessTokenCreate) ProtoMessage()    {}
func (*AccessTokenCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4587e33829422684, []int{4}
}

func (m *AccessTokenCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenCreate.Unmarshal(m, b)
}
func (m *AccessTokenCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenCreate.Marshal(b, m, deterministic)
}
func (m *AccessTokenCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenCreate.Merge(m, src)
}
func (m *AccessTokenCreate) XXX_Size() int {
	return xxx_messageInfo_AccessTokenCreate.Size(m)
}
func (m *AccessTokenCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenCreate.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenCreate proto.InternalMessageInfo

func (m *AccessTokenCreate) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

//status https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
type AccessTokenResponse struct {
	AccessToken          *AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Status               uint32       `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string       `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AccessTokenResponse) Reset()         { *m = AccessTokenResponse{} }
func (m *AccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*AccessTokenResponse) ProtoMessage()    {}
func (*AccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4587e33829422684, []int{5}
}

func (m *AccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenResponse.Unmarshal(m, b)
}
func (m *AccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *AccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenResponse.Merge(m, src)
}
func (m *AccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_AccessTokenResponse.Size(m)
}
func (m *AccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenResponse proto.InternalMessageInfo

func (m *AccessTokenResponse) GetAccessToken() *AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func (m *AccessTokenResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AccessTokenResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*AccessToken)(nil), "access_token_proto.AccessToken")
	proto.RegisterType((*UserID)(nil), "access_token_proto.UserID")
	proto.RegisterType((*AccessTokenCheck)(nil), "access_token_proto.AccessTokenCheck")
	proto.RegisterType((*AccessTokenGet)(nil), "access_token_proto.AccessTokenGet")
	proto.RegisterType((*AccessTokenCreate)(nil), "access_token_proto.AccessTokenCreate")
	proto.RegisterType((*AccessTokenResponse)(nil), "access_token_proto.AccessTokenResponse")
}

func init() {
	proto.RegisterFile("access_token_proto/access_token.proto", fileDescriptor_4587e33829422684)
}

var fileDescriptor_4587e33829422684 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0x4c, 0x4e, 0x4e,
	0x2d, 0x2e, 0x8e, 0x2f, 0xc9, 0xcf, 0x4e, 0xcd, 0x8b, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x47,
	0x16, 0xd2, 0x03, 0x0b, 0x09, 0x09, 0x61, 0x2a, 0x53, 0xf2, 0xe4, 0xe2, 0x76, 0x04, 0x8b, 0x86,
	0x80, 0x04, 0x85, 0xc4, 0xb9, 0xd8, 0x4b, 0x8b, 0x53, 0x8b, 0xe2, 0x33, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xd8, 0x40, 0x5c, 0xcf, 0x14, 0x21, 0x45, 0x2e, 0x1e, 0x64, 0xdd, 0x12,
	0x4c, 0x60, 0x59, 0xee, 0x44, 0x84, 0x5e, 0x25, 0x45, 0x2e, 0xb6, 0x50, 0x90, 0x62, 0x17, 0x9c,
	0xa6, 0x28, 0x85, 0x71, 0x09, 0x20, 0xd9, 0xe6, 0x9c, 0x91, 0x9a, 0x9c, 0x2d, 0xe4, 0x84, 0x66,
	0x32, 0x48, 0x07, 0xb7, 0x91, 0xbc, 0x1e, 0xa6, 0x63, 0xf5, 0x90, 0xf4, 0xa2, 0x5a, 0xed, 0xca,
	0xc5, 0x87, 0x24, 0xe7, 0x9e, 0x5a, 0x22, 0x64, 0x8c, 0xea, 0x04, 0x6e, 0x23, 0x29, 0x6c, 0x06,
	0x42, 0xdc, 0x0b, 0x77, 0x9e, 0x07, 0x97, 0x20, 0xb2, 0xf3, 0x8a, 0x52, 0x13, 0x4b, 0x52, 0xc9,
	0x33, 0xa9, 0x99, 0x91, 0x4b, 0x18, 0xd9, 0xb5, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0xd4,
	0xf0, 0xac, 0x90, 0x18, 0x17, 0x5b, 0x71, 0x49, 0x62, 0x49, 0x69, 0x31, 0x38, 0x12, 0x78, 0x83,
	0xa0, 0x3c, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0x09, 0x66, 0x70, 0x88, 0x83, 0x98, 0x46,
	0x0b, 0x98, 0xb8, 0x84, 0x90, 0x8c, 0x09, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x8a, 0xe0,
	0x62, 0x85, 0x04, 0xbd, 0x0a, 0x01, 0x7b, 0xc1, 0xaa, 0xa4, 0xd4, 0x09, 0xb9, 0x0e, 0xea, 0x39,
	0x25, 0x06, 0xa1, 0x10, 0x2e, 0x66, 0x50, 0xe0, 0x2b, 0x11, 0xd0, 0xe1, 0x9e, 0x5a, 0x42, 0x8a,
	0xa9, 0x51, 0x5c, 0x6c, 0xd0, 0xb8, 0x50, 0x25, 0xe4, 0x60, 0xb0, 0x32, 0x12, 0xcc, 0x76, 0x12,
	0x89, 0xc2, 0x92, 0x2b, 0x92, 0xd8, 0xc0, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xab, 0x75,
	0x7c, 0x6b, 0x59, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccessTokenServiceClient is the client API for AccessTokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccessTokenServiceClient interface {
	//Check
	Check(ctx context.Context, in *AccessTokenCheck, opts ...grpc.CallOption) (*AccessTokenResponse, error)
	//Get
	Get(ctx context.Context, in *AccessTokenGet, opts ...grpc.CallOption) (*AccessTokenResponse, error)
	//UPDATE
	Create(ctx context.Context, in *AccessTokenCreate, opts ...grpc.CallOption) (*AccessTokenResponse, error)
}

type accessTokenServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccessTokenServiceClient(cc *grpc.ClientConn) AccessTokenServiceClient {
	return &accessTokenServiceClient{cc}
}

func (c *accessTokenServiceClient) Check(ctx context.Context, in *AccessTokenCheck, opts ...grpc.CallOption) (*AccessTokenResponse, error) {
	out := new(AccessTokenResponse)
	err := c.cc.Invoke(ctx, "/access_token_proto.AccessTokenService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessTokenServiceClient) Get(ctx context.Context, in *AccessTokenGet, opts ...grpc.CallOption) (*AccessTokenResponse, error) {
	out := new(AccessTokenResponse)
	err := c.cc.Invoke(ctx, "/access_token_proto.AccessTokenService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessTokenServiceClient) Create(ctx context.Context, in *AccessTokenCreate, opts ...grpc.CallOption) (*AccessTokenResponse, error) {
	out := new(AccessTokenResponse)
	err := c.cc.Invoke(ctx, "/access_token_proto.AccessTokenService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessTokenServiceServer is the server API for AccessTokenService service.
type AccessTokenServiceServer interface {
	//Check
	Check(context.Context, *AccessTokenCheck) (*AccessTokenResponse, error)
	//Get
	Get(context.Context, *AccessTokenGet) (*AccessTokenResponse, error)
	//UPDATE
	Create(context.Context, *AccessTokenCreate) (*AccessTokenResponse, error)
}

// UnimplementedAccessTokenServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccessTokenServiceServer struct {
}

func (*UnimplementedAccessTokenServiceServer) Check(ctx context.Context, req *AccessTokenCheck) (*AccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedAccessTokenServiceServer) Get(ctx context.Context, req *AccessTokenGet) (*AccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedAccessTokenServiceServer) Create(ctx context.Context, req *AccessTokenCreate) (*AccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterAccessTokenServiceServer(s *grpc.Server, srv AccessTokenServiceServer) {
	s.RegisterService(&_AccessTokenService_serviceDesc, srv)
}

func _AccessTokenService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessTokenCheck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessTokenServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_token_proto.AccessTokenService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessTokenServiceServer).Check(ctx, req.(*AccessTokenCheck))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessTokenService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessTokenGet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessTokenServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_token_proto.AccessTokenService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessTokenServiceServer).Get(ctx, req.(*AccessTokenGet))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessTokenService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessTokenCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessTokenServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_token_proto.AccessTokenService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessTokenServiceServer).Create(ctx, req.(*AccessTokenCreate))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccessTokenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "access_token_proto.AccessTokenService",
	HandlerType: (*AccessTokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _AccessTokenService_Check_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccessTokenService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccessTokenService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access_token_proto/access_token.proto",
}
